fedora21:
  extends:
    file: OS/docker-compose.yml
    service: fedora21

fc21-service-apache:
  extends:
    file: Services/apache/docker-compose.yml
    service: server

fc21-service-php:
  extends:
    file: Services/php/docker-compose.yml
    service: server

fc21-service-nodejs:
  extends:
    file: Services/nodejs/docker-compose.yml
    service: server

fc21-service-mariadb:
  extends:
    file: Services/mariadb/docker-compose.yml
    service: server

fc21-service-postgres:
  extends:
    file: Services/postgres/docker-compose.yml
    service: server

fc21-service-mongo:
  extends:
    file: Services/mongo/docker-compose.yml
    service: server

fc21-service-ooconv:
  extends:
    file: Services/ooconv/docker-compose.yml
    service: server

fc21-service-memcache:
  extends:
    file: Services/memcache/docker-compose.yml
    service: server

fc21-application-pma:
  build: Applications/phpmyadmin/
  container_name: "application-phpmyadmin"

#fc21-application-rockmongo:
#  build: Applications/rockmongo/
#  container_name: "application-rockmongo"
