fedora22:
  extends:
    file: OS/docker-compose.yml
    service: fedora22

fc22-service-apache:
  extends:
    file: Services/apache/docker-compose.yml
    service: server

fc22-service-php:
  extends:
    file: Services/php/docker-compose.yml
    service: server

fc22-service-nodejs:
  extends:
    file: Services/nodejs/docker-compose.yml
    service: server

fc22-service-mariadb:
  extends:
    file: Services/mariadb/docker-compose.yml
    service: server

fc22-service-postgres:
  extends:
    file: Services/postgres/docker-compose.yml
    service: server

fc22-service-mongo:
  extends:
    file: Services/mongo/docker-compose.yml
    service: server

fc22-service-ooconv:
  extends:
    file: Services/ooconv/docker-compose.yml
    service: server

fc22-service-memcache:
  extends:
    file: Services/memcache/docker-compose.yml
    service: server

fc22_app_pma:
  build: Applications/phpmyadmin/
  container_name: "application-phpmyadmin"

#fc22_app_rockmongo:
#  build: Applications/rockmongo/
#  container_name: "application-rockmongo"
