centos7:
  extends:
    file: OS/docker-compose.yml
    service: centos7

centos7-service-apache:
  extends:
    file: Services/apache/docker-compose.yml
    service: server

centos7-service-php:
  extends:
    file: Services/php/docker-compose.yml
    service: server

centos7-service-nodejs:
  extends:
    file: Services/nodejs/docker-compose.yml
    service: server

centos7-service-mariadb:
  extends:
    file: Services/mariadb/docker-compose.yml
    service: server

centos7-service-postgres:
  extends:
    file: Services/postgres/docker-compose.yml
    service: server

centos7-service-mongo:
  extends:
    file: Services/mongo/docker-compose.yml
    service: server

centos7-service-ooconv:
  extends:
    file: Services/ooconv/docker-compose.yml
    service: server

centos7-service-memcache:
  extends:
    file: Services/memcache/docker-compose.yml
    service: server
    
centos7_couchbase:
  extends:
    file: Services/couchbase/docker-compose.yml
    service: server

centos7-application-pma:
  build: Applications/phpmyadmin/
  container_name: "application-phpmyadmin"

#centos7-application-rockmongo:
#  build: Applications/rockmongo/
#  container_name: "application-rockmongo"
