fedora20:
  build: ./
  container_name: "os-fedora20"
  mem_limit: 1g
  memswap_limit: 1g
  cpu_shares: 2
  restart: "on-failure:2"
  environment:
    CONTAINER_TYPE: "os"
    CONTAINER_SERVICE: "fedora"
    CONTAINER_INSTANCE: "os-fedora20"