server:
  build: ./
  container_name: "fc22-service-apache"
  mem_limit: 500m
  memswap_limit: 500m
  cpu_shares: 2
  restart: "on-failure:2"
  ports:
    - "9201:80"
    - "9202:443"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "apache"
    CONTAINER_INSTANCE: "fc22-service-apache"
    SERVER_NAME: "localhost"
  volumes:
    - "/tmp/container-fc22/logs/apache:/data/logs/apache"
    - "/tmp/container-fc22/apache:/data/apache"
