phpmyadmin:
  build: ./
  container_name: "fc31-application-phpmyadmin"
  mem_limit: 500m
  memswap_limit: 500m
  cpu_shares: 2
  ports:
    - "9215:8080"
#  volumes:
#    - "/tmp/container/memcache/logs:/var/log/httpd:z"
#    - "/tmp/container/phpmyadmin/data:/data:z"
#  command:
#     - "/bin/sx-pma"
#     - "run"
