server:
  build: ./
  container_name: "application-phpmyadmin"
  mem_limit: 500m
  memswap_limit: 500m
  cpu_shares: 2
  restart: "on-failure:2"
  ports:
    - "9215:80"
    - "9216:443"
  environment:
    CONTAINER_TYPE: "application"
    CONTAINER_SERVICE: "phpmyadmin"
    CONTAINER_INSTANCE: "application-phpmyadmin"
    SERVER_NAME: "localhost"
  volumes:
    - "/tmp/container/logs/phpmyadmin:/logs/apache"
    - "/tmp/container/phpmyadmin:/data/apache"