phpmyadmin:
  build: ./
  container_name: "application-phpmyadmin"
  mem_limit: 500m
  memswap_limit: 500m
  cpu_shares: 2
  ports:
    - "9215:8080"
  volumes:
    - "/tmp/container/phpmyadmin:/data"