server:
  build: ./
  container_name: "centos7-service-php"
  mem_limit: 1g
  memswap_limit: 1g
  cpu_shares: 5
  restart: "on-failure:2"
  ports:
    - "9213:80"
    - "9214:443"
  environment:
    CONTAINER_TYPE: "service"
    CONTAINER_SERVICE: "php"
    CONTAINER_INSTANCE: "centos7-service-php"
    SERVER_NAME: "localhost"
  volumes:
    - "/tmp/container-centos7/logs/php:/data/logs/apache"
    - "/tmp/container-centos7/php:/data/apache"
